services:
  honey-dynamic:
    image: ghcr.io/elderflowa/honey-dynamic:latest
    container_name: honey-dynamic
    restart: unless-stopped
    volumes:
      - ./config:/app/dist/config
      - ./icons:/app/dist/img/custom
    ports:
      - "4174:4173"
